# This workflow will build a net80 project on linux
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BidirectionalIterator on [linux-net80]

on:
  push:
    branches: [ "main" ]
    paths: [ 'BidirectionalIterator*/**' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'BidirectionalIterator*/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./BidirectionalIterator/BidirectionalIterator

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --framework net8.0 --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --framework net8.0 --configuration Release --verbosity minimal
