# This workflow will build a net48 project on windows
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: windows-net48

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./SyntaxParser

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --framework net48 --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
